let products = Array.isArray(window.PRODUCTS) ? window.PRODUCTS : [];
let cat = 'All';
const grid=document.querySelector('#grid'),cats=document.querySelector('#cats'),search=document.querySelector('#search'),count=document.querySelector('#count');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderCats(){const a=['All',...new Set(products.map(x=>x.category).filter(Boolean))];cats.innerHTML=a.map(x=>`<button class="cat ${x===cat?'active':''}" data-c="${esc(x)}">${esc(x)}</button>`).join('');cats.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{cat=b.dataset.c;renderCats();render()})}
function render(){const q=search.value.toLowerCase();const list=products.filter(p=>(cat==='All'||p.category===cat)&&(`${p.name} ${p.category} ${p.description}`).toLowerCase().includes(q));count.textContent=`${list.length} product${list.length===1?'':'s'}`;grid.innerHTML=list.map(p=>`<article class="card" data-id="${esc(p.id)}"><img src="${esc(p.image)}" alt="${esc(p.name)}" onerror="this.src='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600"><rect width="100%" height="100%" fill="#eeeeee"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#777" font-family="Arial" font-size="24">Image not found</text></svg>')"><div class="info"><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><span class="view">View product details →</span></div></article>`).join('')||'<p class="empty">No products found.</p>';grid.querySelectorAll('.card').forEach(c=>c.onclick=()=>openProduct(c.dataset.id))}
function openProduct(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;document.querySelector('#mi').src=p.image;document.querySelector('#mi').alt=p.name;document.querySelector('#mc').textContent=p.category;document.querySelector('#mn').textContent=p.name;document.querySelector('#md').textContent=p.description;document.querySelector('#mw').href='https://wa.me/94743839501?text='+encodeURIComponent('Hello Omega Trade Center, I am interested in: '+p.name);document.querySelector('#modal').classList.add('open')}
function close(){document.querySelector('#modal').classList.remove('open')}
document.querySelector('#close').onclick=close;document.querySelector('.backdrop').onclick=close;document.addEventListener('keydown',e=>e.key==='Escape'&&close());search.oninput=render;renderCats();render();
