let products=[];let cat='All';
const grid=document.querySelector('#grid'),cats=document.querySelector('#cats'),search=document.querySelector('#search'),count=document.querySelector('#count');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderCats(){const a=['All',...new Set(products.map(x=>x.category).filter(Boolean))];cats.innerHTML=a.map(x=>`<button class="cat ${x===cat?'active':''}" data-c="${esc(x)}">${esc(x)}</button>`).join('');cats.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{cat=b.dataset.c;renderCats();render()})}
function render(){const q=search.value.toLowerCase();const list=products.filter(p=>(cat==='All'||p.category===cat)&&(`${p.name} ${p.category} ${p.description}`).toLowerCase().includes(q));count.textContent=`${list.length} product${list.length===1?'':'s'}`;grid.innerHTML=list.map(p=>`<article class="card" data-id="${esc(p.id)}"><img src="${esc(p.image)}" alt="${esc(p.name)}"><div class="info"><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><span class="view">View product details →</span></div></article>`).join('')||'<p class="empty">No products found.</p>';grid.querySelectorAll('.card').forEach(c=>c.onclick=()=>openProduct(c.dataset.id))}
function openProduct(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;document.querySelector('#mi').src=p.image;document.querySelector('#mi').alt=p.name;document.querySelector('#mc').textContent=p.category;document.querySelector('#mn').textContent=p.name;document.querySelector('#md').textContent=p.description;document.querySelector('#mw').href='https://wa.me/94743839501?text='+encodeURIComponent('Hello Omega Trade Center, I am interested in: '+p.name);document.querySelector('#modal').classList.add('open')}
function close(){document.querySelector('#modal').classList.remove('open')}
document.querySelector('#close').onclick=close;document.querySelector('.backdrop').onclick=close;document.addEventListener('keydown',e=>e.key==='Escape'&&close());search.oninput=render;
(async()=>{try{products=await omegaLoadProducts();renderCats();render();}catch(e){console.error(e);grid.innerHTML='<p class="empty">Unable to load products. Please check the database setup.</p>';count.textContent='';}})();
