-- OMEGA TRADE CENTER v4
-- Run this entire file in Supabase > SQL Editor.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text default '',
  image text not null,
  image_path text,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Public can view products" on public.products;
create policy "Public can view products"
on public.products for select
using (true);

drop policy if exists "Public can add products" on public.products;
create policy "Public can add products"
on public.products for insert
to anon
with check (true);

drop policy if exists "Public can delete products" on public.products;
create policy "Public can delete products"
on public.products for delete
to anon
using (true);

insert into public.products (name, category, description, image)
select * from (values
('1.8L Rice Cooker','Rice Cookers','Product description will be added later.','https://placehold.co/800x800/f1f2f4/555?text=Product+Photo'),
('Stand Fan','Fans','Product description will be added later.','https://placehold.co/800x800/f1f2f4/555?text=Product+Photo'),
('Mixer Grinder','Blenders & Grinders','Product description will be added later.','https://placehold.co/800x800/f1f2f4/555?text=Product+Photo'),
('4 Burner Gas Cooker','Gas Cookers','Product description will be added later.','https://placehold.co/800x800/f1f2f4/555?text=Product+Photo')
) as v(name,category,description,image)
where not exists (select 1 from public.products);

insert into storage.buckets (id, name, public)
values ('product-images','product-images',true)
on conflict (id) do update set public=true;

drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
on storage.objects for select
to public
using (bucket_id = 'product-images');

drop policy if exists "Public can upload product images" on storage.objects;
create policy "Public can upload product images"
on storage.objects for insert
to anon
with check (bucket_id = 'product-images');

drop policy if exists "Public can delete product images" on storage.objects;
create policy "Public can delete product images"
on storage.objects for delete
to anon
using (bucket_id = 'product-images');
